exec:
  name: Exec
  description: Run python code from file or from source
  fields:
    file:
      name: File
      description: Relative path to file (optional)
      example: path_to/filename.py
      selector:
        text:
    source:
      name: Source
      description: Source of python script (optional)
      example: "logger.warning('Hello from script')"
      selector:
        text:
    cache:
      name: Cache
      description: Use cache when loading code (optional, default true)
      example: true
      selector:
        boolean:
