# Describes the format for available python_script services

exec:
  description: Run python code from file or from source
  fields:
    file:
      description: Relative path to file (optional)
      example: path_to/filename.py
    source:
      description: Source of python script (optional)
      example: "logger.warning('Hello from script')"
    cache:
      description: Use cache when loading code (optional, default true)
      example: true
